Update etc/init.d__adhocracy_services.sh.template

diff --git a/etc/init.d__adhocracy_services.sh.template b/etc/init.d__adhocracy_services.sh.template
--- a/etc/init.d__adhocracy_services.sh.template
+++ b/etc/init.d__adhocracy_services.sh.template
@@ -19,6 +19,28 @@ SCRIPTNAME=/etc/init.d/$NAME
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+# Load the VERBOSE setting and other rcS variables
+if [ -r /lib/init/vars.sh ] ; then
+	. /lib/init/vars.sh
+else
+	VERBOSE="no"
+fi
+
+if [ -r /lib/lsb/init-functions ] ; then
+	. /lib/lsb/init-functions
+else
+	log_daemon_msg() {
+		echo $!
+	}
+	log_end_msg() {
+		echo $!
+	}
+fi
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
 in_virtualenv() {
 	su "$USER" -c "cd $DIR && . bin/activate && $*"
 	return $?
@@ -60,11 +82,21 @@ do_status() {
 
 case "$1" in
   start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
-        ;;
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
-        ;;
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   status)
 	do_status
 	exit $?
@@ -74,14 +106,20 @@ case "$1" in
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
 		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
 		;;
 	  *)
 		# Failed to stop
-                echo "Failed to stop."
+		log_end_msg 1
 		;;
 	esac
 	;;
